/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LcsRouteImport } from './routes/lcs'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as BankLcIdRouteImport } from './routes/bank.$lcId'
import { Route as CustomsLcIdRouteImport } from './routes/customs.$lcId'
import { Route as DocumentsLcIdRouteImport } from './routes/documents.$lcId'
import { Route as LcsIndexRouteImport } from './routes/lcs.index'
import { Route as LcsLcIdRouteImport } from './routes/lcs.$lcId'
import { Route as LcsNewRouteImport } from './routes/lcs.new'
import { Route as QueueBankRouteImport } from './routes/queue.bank'
import { Route as QueueCustomsRouteImport } from './routes/queue.customs'
import { Route as QueueDocumentsRouteImport } from './routes/queue.documents'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LcsRoute = LcsRouteImport.update({
  id: '/lcs',
  path: '/lcs',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const BankLcIdRoute = BankLcIdRouteImport.update({
  id: '/bank/$lcId',
  path: '/bank/$lcId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomsLcIdRoute = CustomsLcIdRouteImport.update({
  id: '/customs/$lcId',
  path: '/customs/$lcId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsLcIdRoute = DocumentsLcIdRouteImport.update({
  id: '/documents/$lcId',
  path: '/documents/$lcId',
  getParentRoute: () => rootRouteImport,
} as any)
const LcsIndexRoute = LcsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LcsRoute,
} as any)
const LcsLcIdRoute = LcsLcIdRouteImport.update({
  id: '/$lcId',
  path: '/$lcId',
  getParentRoute: () => LcsRoute,
} as any)
const LcsNewRoute = LcsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LcsRoute,
} as any)
const QueueBankRoute = QueueBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => QueueRoute,
} as any)
const QueueCustomsRoute = QueueCustomsRouteImport.update({
  id: '/customs',
  path: '/customs',
  getParentRoute: () => QueueRoute,
} as any)
const QueueDocumentsRoute = QueueDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => QueueRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lcs': typeof LcsRouteWithChildren
  '/queue': typeof QueueRouteWithChildren
  '/bank/$lcId': typeof BankLcIdRoute
  '/customs/$lcId': typeof CustomsLcIdRoute
  '/documents/$lcId': typeof DocumentsLcIdRoute
  '/lcs/$lcId': typeof LcsLcIdRoute
  '/lcs/new': typeof LcsNewRoute
  '/queue/bank': typeof QueueBankRoute
  '/queue/customs': typeof QueueCustomsRoute
  '/queue/documents': typeof QueueDocumentsRoute
  '/lcs/': typeof LcsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/queue': typeof QueueRouteWithChildren
  '/bank/$lcId': typeof BankLcIdRoute
  '/customs/$lcId': typeof CustomsLcIdRoute
  '/documents/$lcId': typeof DocumentsLcIdRoute
  '/lcs/$lcId': typeof LcsLcIdRoute
  '/lcs/new': typeof LcsNewRoute
  '/queue/bank': typeof QueueBankRoute
  '/queue/customs': typeof QueueCustomsRoute
  '/queue/documents': typeof QueueDocumentsRoute
  '/lcs': typeof LcsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lcs': typeof LcsRouteWithChildren
  '/queue': typeof QueueRouteWithChildren
  '/bank/$lcId': typeof BankLcIdRoute
  '/customs/$lcId': typeof CustomsLcIdRoute
  '/documents/$lcId': typeof DocumentsLcIdRoute
  '/lcs/$lcId': typeof LcsLcIdRoute
  '/lcs/new': typeof LcsNewRoute
  '/queue/bank': typeof QueueBankRoute
  '/queue/customs': typeof QueueCustomsRoute
  '/queue/documents': typeof QueueDocumentsRoute
  '/lcs/': typeof LcsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lcs'
    | '/queue'
    | '/bank/$lcId'
    | '/customs/$lcId'
    | '/documents/$lcId'
    | '/lcs/$lcId'
    | '/lcs/new'
    | '/queue/bank'
    | '/queue/customs'
    | '/queue/documents'
    | '/lcs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/queue'
    | '/bank/$lcId'
    | '/customs/$lcId'
    | '/documents/$lcId'
    | '/lcs/$lcId'
    | '/lcs/new'
    | '/queue/bank'
    | '/queue/customs'
    | '/queue/documents'
    | '/lcs'
  id:
    | '__root__'
    | '/'
    | '/lcs'
    | '/queue'
    | '/bank/$lcId'
    | '/customs/$lcId'
    | '/documents/$lcId'
    | '/lcs/$lcId'
    | '/lcs/new'
    | '/queue/bank'
    | '/queue/customs'
    | '/queue/documents'
    | '/lcs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LcsRoute: typeof LcsRouteWithChildren
  QueueRoute: typeof QueueRouteWithChildren
  BankLcIdRoute: typeof BankLcIdRoute
  CustomsLcIdRoute: typeof CustomsLcIdRoute
  DocumentsLcIdRoute: typeof DocumentsLcIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lcs': {
      id: '/lcs'
      path: '/lcs'
      fullPath: '/lcs'
      preLoaderRoute: typeof LcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank/$lcId': {
      id: '/bank/$lcId'
      path: '/bank/$lcId'
      fullPath: '/bank/$lcId'
      preLoaderRoute: typeof BankLcIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customs/$lcId': {
      id: '/customs/$lcId'
      path: '/customs/$lcId'
      fullPath: '/customs/$lcId'
      preLoaderRoute: typeof CustomsLcIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$lcId': {
      id: '/documents/$lcId'
      path: '/documents/$lcId'
      fullPath: '/documents/$lcId'
      preLoaderRoute: typeof DocumentsLcIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lcs/': {
      id: '/lcs/'
      path: '/'
      fullPath: '/lcs/'
      preLoaderRoute: typeof LcsIndexRouteImport
      parentRoute: typeof LcsRoute
    }
    '/lcs/$lcId': {
      id: '/lcs/$lcId'
      path: '/$lcId'
      fullPath: '/lcs/$lcId'
      preLoaderRoute: typeof LcsLcIdRouteImport
      parentRoute: typeof LcsRoute
    }
    '/lcs/new': {
      id: '/lcs/new'
      path: '/new'
      fullPath: '/lcs/new'
      preLoaderRoute: typeof LcsNewRouteImport
      parentRoute: typeof LcsRoute
    }
    '/queue/bank': {
      id: '/queue/bank'
      path: '/bank'
      fullPath: '/queue/bank'
      preLoaderRoute: typeof QueueBankRouteImport
      parentRoute: typeof QueueRoute
    }
    '/queue/customs': {
      id: '/queue/customs'
      path: '/customs'
      fullPath: '/queue/customs'
      preLoaderRoute: typeof QueueCustomsRouteImport
      parentRoute: typeof QueueRoute
    }
    '/queue/documents': {
      id: '/queue/documents'
      path: '/documents'
      fullPath: '/queue/documents'
      preLoaderRoute: typeof QueueDocumentsRouteImport
      parentRoute: typeof QueueRoute
    }
  }
}

interface LcsRouteChildren {
  LcsLcIdRoute: typeof LcsLcIdRoute
  LcsNewRoute: typeof LcsNewRoute
  LcsIndexRoute: typeof LcsIndexRoute
}

const LcsRouteChildren: LcsRouteChildren = {
  LcsLcIdRoute: LcsLcIdRoute,
  LcsNewRoute: LcsNewRoute,
  LcsIndexRoute: LcsIndexRoute,
}

const LcsRouteWithChildren = LcsRoute._addFileChildren(LcsRouteChildren)

interface QueueRouteChildren {
  QueueBankRoute: typeof QueueBankRoute
  QueueCustomsRoute: typeof QueueCustomsRoute
  QueueDocumentsRoute: typeof QueueDocumentsRoute
}

const QueueRouteChildren: QueueRouteChildren = {
  QueueBankRoute: QueueBankRoute,
  QueueCustomsRoute: QueueCustomsRoute,
  QueueDocumentsRoute: QueueDocumentsRoute,
}

const QueueRouteWithChildren = QueueRoute._addFileChildren(QueueRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LcsRoute: LcsRouteWithChildren,
  QueueRoute: QueueRouteWithChildren,
  BankLcIdRoute: BankLcIdRoute,
  CustomsLcIdRoute: CustomsLcIdRoute,
  DocumentsLcIdRoute: DocumentsLcIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
